### ISSUE TITLE
License Related

### ISSUE THREAD

**Issue by Vikky98** [coalaura/opfw-admin#10]
**Is your feature request related to a problem? Please describe.**
Now we've multiple ingame Licenses available which can be given to players which unlocks new perks for them . suppose some player has multiple license on him and when it comes to removing any certain license via web panel , we need to remove all of them at once and then add one by one remaining. 

**Describe the solution you'd like**
While removing license if we get an option like checkbox so we can select which license is to be removed and which isn't. 

**Describe alternatives you've considered**
or after clicking remove license it'll ask us to select which license we want to remove using some button form or something.

**Additional context**
NaN

**Comment by coalaura** [comment]
done
