### ISSUE TITLE
Player Status bug

### ISSUE THREAD

**Issue by Vikky98** [coalaura/opfw-admin#11]
**Which clusters panel is this on?**
c8

**Describe the bug**
While Checking live map in web panel , some players show as dead in it and when i click on that skull icon , a page opens up showing whole info about that player and in that player isn't dead . may be checked in at hospital or something but his blip on live map shows as skull which is used for dead player. this happen with few players tho. like 30-70 chances.

**To Reproduce**
1. Go to 'Data section in live map'
2. Click on 'Live map and observe players blip '
3. click on any dead player blip and check players info page.

**Expected behavior**
Player blip must be changed as soon as he checked in or revived . ( again as mentioned above happens some time )

**Screenshots**
one with bug : 
https://i.imgur.com/2s31HPR.png
https://i.imgur.com/9Uu9Qv4.png
one without Bug : 
https://i.imgur.com/1BbnMls.png
https://i.imgur.com/tetiBqd.png

**Comment by coalaura** [comment]
thats a framework and not a panel bug
