### ISSUE TITLE
manage eoles for staff

### ISSUE THREAD

**Issue by EDNUGAR** [coalaura/opfw-admin#12]
**Which clusters panel is this on?**
c4

I Have SuperAdmin rol and i cant see the tool. 
The tool to manage roles for a user is not available.

**Screenshots**
![screenc4](https://github.com/coalaura/opfw-admin/assets/150629043/37a3318e-3c20-4e3e-a1ee-4e2f213043cc)

**Comment by coalaura** [comment]
cause its not enabled on that cluster

**Comment by EDNUGAR** [comment]
so... how can I manage a role?
