### ISSUE TITLE
Twitter link button to go to profile missing

### ISSUE THREAD

**Issue by TacticalTyl3r** [coalaura/opfw-admin#18]
**Which clusters panel is this on?**
c3

**Describe the bug**
When you click on a person's twitter post then go to the character you do not get any buttons to go to the player's main profile

**To Reproduce**
1. Go to 'twitter feed'
2. Click on 'character's account'
3. Look for button to main player account
4. See no buttons and feel sad 

**Expected behavior**
When you click on the character you do not get the button on the top to go back to the character's main profile

**Screenshots**
Twitter Feed: https://i.imgur.com/c9BpqiU.png
Character Panel with no buttons: https://i.imgur.com/PmeQQtu.png
Normal Character Panel with buttons: https://i.imgur.com/aBeS3LP.png

**Comment by coalaura** [comment]
fixed
