### ISSUE TITLE
Tattoo Removal

### ISSUE THREAD

**Issue by antonettedorado98** [coalaura/opfw-admin#20]
**Which clusters panel is this on?**
c3

**Describe the bug**
Tattoo Removals not working. Panel would say that the tattoo has been successfully removed, but the character doesnt change in game.

**To Reproduce**
1. Go to 'Character Page'
2. Click on 'Tattoo Removal'
3. Scroll down to 'any option'
4. See 'success message'
5. In server, character doesnt change.

**Expected behavior**
Character to change and rid of specific tattoo.

**Comment by coalaura** [comment]
The panel will remove the tattoos via the database. However, tattoos wont refresh ingame if they are only changed in the database, so the panel also attempts to tell the FiveM server to reload the characters tattoos.

![yes](https://i.shrt.day/AR6SSANF85.webp)

If the ingame refresh was successful you will see this message. If this message is not there, the panel failed to communicate with the server (i cant fix this). If the ingame refresh is unsuccessful, softnapping (unloading and loading back in) will also refresh the tattoos.
