### ISSUE TITLE
Let me see players outfits from the panel

### ISSUE THREAD

**Issue by scufflord** [coalaura/opfw-admin#21]
**Is your feature request related to a problem? Please describe.**
NAH FAM

**Describe the solution you'd like**
Since we already have stored pictures of players outfits could we add the ability to see those pictures on the panel to allow us to easily identify people from clips and screenshots

**Describe alternatives you've considered**
idk fam

**Additional context**
put like a drop down here with a little picture display next to it kinda like how the cars are.

https://i.ibb.co/gtMsKtY/B7-Qu0-OKe5-P.png

**Comment by coalaura** [comment]
no cause i want to keep some level of privacy, same reason you dont see the names either
