### ISSUE TITLE
Reskin Logs

### ISSUE THREAD

**Issue by Thales1732** [coalaura/opfw-admin#24]
**Is your feature request related to a problem? Please describe.**
Yes someone paid for a reskin and after reskin was done and they changed outfits they said the reskin went back to original character I tested this and everything worked as it seems.

**Describe the solution you'd like**
A log kind of like los santos customs to see modifications to cars but for re skin to see what the player did

**Describe alternatives you've considered**
No other alternatives I could ask the player what was changed on the character but logs for it like LS Customs would be nice just not sure how hard it would be to do to.

**Additional context**

**Comment by coalaura** [comment]
no, this would just store massive amounts of data in the database for the 1 case in 4 years where it may be useful to 1 person
