### ISSUE TITLE
Server is shown offline in C3 Panel

### ISSUE THREAD

**Issue by Thales1732** [coalaura/opfw-admin#25]
**Which clusters panel is this on?**
c3

**Describe the bug**
Panel isn't communicating with international server.

**To Reproduce**
Go to panel lol
Expected behavior
No workie :( so no features that connect to server work.

![image](https://github.com/user-attachments/assets/b9132b43-782d-429d-bd5e-e70359c63f00)

**Comment by coalaura** [comment]
cool
