### ISSUE TITLE
Bug with inventory logs item name display

### ISSUE THREAD

**Issue by CaptSpider4** [coalaura/opfw-admin#26]
**Which clusters panel is this on?**
c8

**Describe the bug**
Inventory logs showing half name of items ( 1st word of item name )

**To Reproduce**

Go to /inventory/logs/inventory_name:inventory_id

**Expected behavior**
Full name of items should be displayed

**Screenshots**
https://i.imgur.com/ZAvYN89.png

Probably issue with this item details parsing https://github.com/coalaura/opfw-admin/blob/master/resources/js/Pages/Inventories/Logs.vue#L161

**Comment by coalaura** [comment]
fixed
