### ISSUE TITLE
Filtering option in Inventory Logs Route

### ISSUE THREAD

**Issue by CaptSpider4** [coalaura/opfw-admin#27]
**Is your feature request related to a problem? Please describe.**
Abel to filter inventory logs in `/inventory/logs/{inventory}` route

**Describe the solution you'd like**
Able to filter out inventory logs based on filters like, source player, from inventory, to inventory, after and before time.

I know these things can be done in `/logs` route however sometimes inventory logs is better in checking inventory movements but because we cant filter out things we have to either scroll multiple pages or kinda struggle in main server logs 

Also able to see `Item Given` action logs in inventory logs page. Right now only `Item Moved` actions are shows in inventory logs https://i.imgur.com/JwIxwFK.png

**Comment by coalaura** [comment]
No, thats not part of those logs. They just give you a quick overview and if you need more info you use the server logs
