### ISSUE TITLE
Sidebar update button bug

### ISSUE THREAD

**Issue by CaptSpider4** [coalaura/opfw-admin#28]
**Which clusters panel is this on?**
c8

**Describe the bug**
When SIdebar collapsed update buttons still displays

**Expected behavior**
Update button shouldn't displayed like others

**Screenshots**
https://i.imgur.com/rzwfT4S.png

**Comment by coalaura** [comment]
Its hidden for me when i collaps the sidebar

![yes](https://i.shrt.day/HTJY42HW53.webp)

**Comment by CaptSpider4** [comment]
I think its because it only shows when there is a update ( we use custom hosted panel in our subdivision ) its not so important just the bug i noticed

**Comment by CaptSpider4** [comment]
idk much about vue.js however i guess it might be because of this 
https://i.imgur.com/BJMwEHA.png This perticular one doesn't exist in update button so might be causing this bug

**Comment by coalaura** [comment]
oh yeah i confused the buttons sorry, should be fixed now
