### ISSUE TITLE
Panel Permission Changes

### ISSUE THREAD

**Issue by MorningBelle** [coalaura/opfw-admin#3]
**Is your feature request related to a problem? Please describe.**
No.
A modification to the Admin Panel that will allow access restrictions based on the level a user is at

**Describe the solution you'd like**
Having it where the server that has access to the panel can change what level of access to the panel a user gets(A regular staff member not having access, but senior staff would be able to, based on discord connected).
**Describe alternatives you've considered**
Remove the clickable link to identifiers in /log or /panel. But if the person has the URL, this would be a moot change. 

**Additional context**
Though giving the url out to specific people who are in proper staff positions expected to have access to the panel, anyone without the url who is at a lower level of staff can still access the panel by doing /log [serverID] or  /panel [serverID] and clicking on the player's license to open up the panel.

**Comment by coalaura** [comment]
i don't think this is needed. Staff are staff staff should have access to the panel. If people abuse those perms they shouldn't be staff
