### ISSUE TITLE
 ERROR WHEN LOADING PLAYER LIST INTO THE DASHBOARD

### ISSUE THREAD

**Issue by EDNUGAR** [coalaura/opfw-admin#31]
**Which clusters panel is this on?**
c25

**Describe the bug**
I can't see the list of current online players in the player panels

**To Reproduce**

**Expected behavior**

**Screenshots**
https://github.com/user-attachments/assets/329884af-8679-4ce3-8427-3da0b78aecb0

**Comment by coalaura** [comment]
yeah thats not a feature, you can use the livemap if you need to see who is online

**Comment by EDNUGAR** [comment]
all good, thank you
