### ISSUE TITLE
[ADD] Discord authentification

### ISSUE THREAD

**Issue by Loumout** [coalaura/opfw-admin#32]
**Is your feature request related to a problem? Please describe.**
No it's not a problem, it's an option to potentially add

**Describe the solution you'd like**
It would be perfect to add an option to choose between steam auth and discord auth, cause today, Fivem server mostly use rockstar auth

**Describe alternatives you've considered**
No alternative, it's a new option

**Additional context**
/

**Comment by coalaura** [comment]
We don't use steam for authentication? We already use discord...
