### ISSUE TITLE
Wipe inventory/property button

### ISSUE THREAD

**Issue by KaiEagle** [coalaura/opfw-admin#4]
**Is your feature request related to a problem? Please describe.**
A wipe or delete button on top of the inventory contents so it's easy to wipe someone inventory with just a key 👍🏼 

**Additional context**
Something like this will do
https://img.kaieagle.me/u/3TLOKGC.png

**Comment by coalaura** [comment]
bet

**Comment by coalaura** [comment]
this wont really work properly for a bunch of inventories cause it would be desynced ingame
