### ISSUE TITLE
Separate Arena logs

### ISSUE THREAD

**Issue by Masik52** [coalaura/opfw-admin#5]
**Is your feature request related to a problem? Please describe.**
with the amount of time people spend in arena, if we get a report where there's no ID given of the offending party it can be like trying to find a needle in a haystack to locate the person in question via kill logs, damage logs etc.  

**Describe the solution you'd like**
have logging separate for the arena garbage

**Comment by coalaura** [comment]
It would be a shit load of work requiring changes to the framework and the panel for a feature i don't deem THAT needed, so no
