### ISSUE TITLE
License Identifier

### ISSUE THREAD

**Issue by KaiEagle** [coalaura/opfw-admin#6]
**Which clusters panel is this on?**
c8

**Describe the bug**
When clicking on copy license identifier for a user. It just doesn't copy at all.

**To Reproduce**
Should copy the license identifier of the user you want to copy.

**Screenshots**
![brave_hOyxOAMA6C](https://github.com/coalaura/opfw-admin/assets/29286961/a34f155e-63c2-40ab-85e9-13e36af8acdb)

**Comment by Vikky98** [comment]
Now clicking on that icon copies users discord id instead of License identifier.

**Comment by coalaura** [comment]
fixed
