### ISSUE TITLE
c17 Screenshot Error

### ISSUE THREAD

**Issue by MorningBelle** [coalaura/opfw-admin#7]
**Which clusters panel is this on?**
cluster 17 - c17

**Describe the bug**
When trying to screenshot or record, the panel fails to do so 

**To Reproduce**
1. Go to any active player in the server
2. Click on Screenshot or Record button
3 See error

**Expected behavior**
For the panel to screenshot the client's view point

**Screenshots**
![image](https://github.com/coalaura/opfw-admin/assets/92956585/3288cb1f-d4a5-42ce-a2b8-48f23b440e04)

**Comment by Vikky98** [comment]
Same issue with C8 cluster also.

**Comment by coalaura** [comment]
should be fixed now
