### ISSUE TITLE
Mute / Unmute option

### ISSUE THREAD

**Issue by CaptSpider4** [coalaura/opfw-admin#8]
**Is your feature request related to a problem? Please describe.**
Able to Mute & Unmute from Player profile similar to ban

**Describe the solution you'd like**
So there should be a way to mute & unmute someone from OOC using panel

**Comment by coalaura** [comment]
You can now unmute players from the panel, however i don't see a need for muting from the panel since mutes only affect you ingame so they should be given ingame

![yes](https://i.shrt.day/EZ35P3OEP6.webp)
