### ISSUE TITLE
Timer on Licenses

### ISSUE THREAD

**Issue by Vikky98** [coalaura/opfw-admin#9]
**Is your feature request related to a problem? Please describe.**
With current license system we've different license like weapon , hunting , mining and much more but all of them are indefinite. And in our subdivision we rp it as license for specific time validity after that it'll be removed.

**Describe the solution you'd like**
I would like to request for timer on Licenses also same ban toggle timer option on banning system where we ban player for specific time .

**Describe alternatives you've considered**
Nothing atm.

**Additional context**
NaN.

**Comment by coalaura** [comment]
You can remove the license once the time has run out
